In [1]:
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import analysis_parameters as ap

chunks = {"Xdim":1024, "time":30}

GEOS is a topdown model

# Part 1

In [11]:
pthick = xr.open_dataset(ap.get_file("GEOS","TWP_3D","pthick"), chunks=chunks).pthick
pthick[0,:,0].values/100

array([3.25724948e-03, 3.99275078e-03, 4.75000031e-03, 5.49999950e-03,
       6.36085495e-03, 7.37242214e-03, 8.72542895e-03, 1.04286578e-02,
       1.22228814e-02, 1.45382024e-02, 1.69355962e-02, 1.98861696e-02,
       2.30154507e-02, 2.67053414e-02, 3.07730101e-02, 3.53695117e-02,
       4.05479819e-02, 4.60413359e-02, 5.25785834e-02, 5.92263043e-02,
       6.71718568e-02, 7.53114298e-02, 8.45024511e-02, 9.44644958e-02,
       1.05120160e-01, 1.17136382e-01, 1.29429698e-01, 1.43253863e-01,
       1.57765657e-01, 1.73239142e-01, 1.90374762e-01, 2.07925409e-01,
       2.27082372e-01, 2.47283787e-01, 2.68453062e-01, 2.91449279e-01,
       3.15142214e-01, 3.40230703e-01, 3.67102057e-01, 3.94682020e-01,
       4.23972487e-01, 4.54669505e-01, 4.86365974e-01, 5.19951165e-01,
       5.54801047e-01, 5.90806901e-01, 6.28690779e-01, 6.67818010e-01,
       7.08168328e-01, 7.50410140e-01, 7.93970346e-01, 8.38754892e-01,
       8.85314941e-01, 9.33367908e-01, 9.82572019e-01, 1.03339350e+00,
      

In [17]:
# zg = xr.open_dataset(ap.get_file("GEOS","TWP_3D","zg"), chunks=chunks).zg.sel(time=pthick.time)
# zg[0,:,0].values/1000

In [23]:
pthick_cumsum_neg = (-1*pthick[:,::-1]).cumsum(axis=1)
pthick_cumsum_neg
# pthick_cumsum_neg.mean(axis=(0,1)).plot()

<xarray.DataArray 'pthick' (time: 720, lev: 181, Xdim: 97152)>
dask.array<nancumsum, shape=(720, 181, 97152), dtype=float32, chunksize=(30, 181, 1024), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2020-01-30 ... 2020-02-28T23:00:00
    lons     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
    lats     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
  * lev      (lev) float64 181.0 180.0 179.0 178.0 177.0 ... 5.0 4.0 3.0 2.0 1.0
Dimensions without coordinates: Xdim

In [ ]:
pthick_cumsum_neg.to_netcdf("/scratch/b/b380883/pthick_cumsum_neg_geos.nc")

# Part 2


Reset kernel and run from here

In [2]:
pthick_cumsum_neg = xr.open_dataset("/scratch/b/b380883/pthick_cumsum_neg_geos.nc", chunks=chunks).pthick
pthick_cumsum = pthick_cumsum_neg[:,::-1]
pthick_cumsum

<xarray.DataArray 'pthick' (time: 720, lev: 181, Xdim: 97152)>
dask.array<getitem, shape=(720, 181, 97152), dtype=float32, chunksize=(30, 181, 1024), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2020-01-30 ... 2020-02-28T23:00:00
    lons     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
    lats     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
  * lev      (lev) float64 1.0 2.0 3.0 4.0 5.0 ... 177.0 178.0 179.0 180.0 181.0
Dimensions without coordinates: Xdim

In [ ]:
pthick_cumsum.to_netcdf("/scratch/b/b380883/twp_geos_pthick_cumsum.nc")

# Part 3


In [2]:
pthick_cumsum = xr.open_dataset("/scratch/b/b380883/pthick_cumsum_neg_geos.nc", chunks=chunks).pthick
pthick_cumsum = pthick_cumsum[:,::-1]
pthick_cumsum

<xarray.DataArray 'pthick' (time: 720, lev: 181, Xdim: 97152)>
dask.array<getitem, shape=(720, 181, 97152), dtype=float32, chunksize=(30, 181, 1024), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2020-01-30 ... 2020-02-28T23:00:00
    lons     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
    lats     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
  * lev      (lev) float64 1.0 2.0 3.0 4.0 5.0 ... 177.0 178.0 179.0 180.0 181.0
Dimensions without coordinates: Xdim

In [3]:
pthick_cumsum[20,:,20].values

array([-100697.984  , -100697.66   , -100697.26   , -100696.78   ,
       -100696.234  , -100695.6    , -100694.87   , -100693.99   ,
       -100692.95   , -100691.734  , -100690.28   , -100688.586  ,
       -100686.59   , -100684.29   , -100681.62   , -100678.54   ,
       -100675.     , -100670.945  , -100666.34   , -100661.086  ,
       -100655.164  , -100648.445  , -100640.914  , -100632.46   ,
       -100623.016  , -100612.5    , -100600.79   , -100587.84   ,
       -100573.516  , -100557.74   , -100540.42   , -100521.38   ,
       -100500.59   , -100477.88   , -100453.16   , -100426.31   ,
       -100397.164  , -100365.65   , -100331.625  , -100294.914  ,
       -100255.445  , -100213.05   , -100167.58   , -100118.945  ,
       -100066.95   , -100011.48   ,  -99952.4    ,  -99889.53   ,
        -99822.75   ,  -99751.93   ,  -99676.89   ,  -99597.49   ,
        -99513.62   ,  -99425.086  ,  -99331.75   ,  -99233.49   ,
        -99130.16   ,  -99021.555  ,  -98907.586  ,  -98788.1 

In [4]:
pres_sfc = xr.open_dataset(ap.get_file("GEOS","TWP","ps"), chunks=chunks).ps.sel(time=pthick_cumsum.time)
# pres_sfc = pres_sfc.expand_dims({"lev":181}, axis=1).assign_coords({"lev":pthick_cumsum.lev})
pres_sfc

<xarray.DataArray 'ps' (time: 720, Xdim: 97152)>
dask.array<getitem, shape=(720, 97152), dtype=float32, chunksize=(8, 1024), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2020-01-30 ... 2020-02-28T23:00:00
    lons     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
    lats     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
Dimensions without coordinates: Xdim
Attributes:
    standard_name:  surface_air_pressure
    long_name:      surface_pressure
    units:          Pa
    CDI_grid_type:  unstructured
    origin:         PS

In [5]:
pres_sfc.shape, pthick_cumsum.shape

((720, 97152), (720, 181, 97152))

In [6]:
pa = pres_sfc.values[:,np.newaxis,:] + pthick_cumsum
pa

<xarray.DataArray 'pthick' (time: 720, lev: 181, Xdim: 97152)>
dask.array<add, shape=(720, 181, 97152), dtype=float32, chunksize=(30, 181, 1024), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2020-01-30 ... 2020-02-28T23:00:00
    lons     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
    lats     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
  * lev      (lev) float64 1.0 2.0 3.0 4.0 5.0 ... 177.0 178.0 179.0 180.0 181.0
Dimensions without coordinates: Xdim

In [7]:
pres_sfc[20,20].values, pthick_cumsum[20,:,20].values

(array(100699., dtype=float32),
 array([-100697.984  , -100697.66   , -100697.26   , -100696.78   ,
        -100696.234  , -100695.6    , -100694.87   , -100693.99   ,
        -100692.95   , -100691.734  , -100690.28   , -100688.586  ,
        -100686.59   , -100684.29   , -100681.62   , -100678.54   ,
        -100675.     , -100670.945  , -100666.34   , -100661.086  ,
        -100655.164  , -100648.445  , -100640.914  , -100632.46   ,
        -100623.016  , -100612.5    , -100600.79   , -100587.84   ,
        -100573.516  , -100557.74   , -100540.42   , -100521.38   ,
        -100500.59   , -100477.88   , -100453.16   , -100426.31   ,
        -100397.164  , -100365.65   , -100331.625  , -100294.914  ,
        -100255.445  , -100213.05   , -100167.58   , -100118.945  ,
        -100066.95   , -100011.48   ,  -99952.4    ,  -99889.53   ,
         -99822.75   ,  -99751.93   ,  -99676.89   ,  -99597.49   ,
         -99513.62   ,  -99425.086  ,  -99331.75   ,  -99233.49   ,
         -99130.

In [8]:
pa[20,:,20].values

array([1.01562500e+00, 1.34375000e+00, 1.74218750e+00, 2.21875000e+00,
       2.76562500e+00, 3.39843750e+00, 4.13281250e+00, 5.00781250e+00,
       6.04687500e+00, 7.26562500e+00, 8.71875000e+00, 1.04140625e+01,
       1.24062500e+01, 1.47109375e+01, 1.73828125e+01, 2.04609375e+01,
       2.40000000e+01, 2.80546875e+01, 3.26562500e+01, 3.79140625e+01,
       4.38359375e+01, 5.05546875e+01, 5.80859375e+01, 6.65390625e+01,
       7.59843750e+01, 8.65000000e+01, 9.82109375e+01, 1.11156250e+02,
       1.25484375e+02, 1.41257812e+02, 1.58578125e+02, 1.77617188e+02,
       1.98406250e+02, 2.21117188e+02, 2.45843750e+02, 2.72687500e+02,
       3.01835938e+02, 3.33351562e+02, 3.67375000e+02, 4.04085938e+02,
       4.43554688e+02, 4.85953125e+02, 5.31421875e+02, 5.80054688e+02,
       6.32046875e+02, 6.87523438e+02, 7.46601562e+02, 8.09468750e+02,
       8.76250000e+02, 9.47070312e+02, 1.02210938e+03, 1.10150781e+03,
       1.18538281e+03, 1.27391406e+03, 1.36725000e+03, 1.46550781e+03,
      

In [ ]:
pa = pa.compute()

In [ ]:
pa

In [11]:
pa = pa.assign_attrs({"standard_name":"air_pressure",
                          "long_name":"pressure_of_air_at_levs",
                          "method":"pthick cumulatively subtracted from pressure at the surface",
                          "unit":"Pa"})
pa

<xarray.DataArray 'pthick' (time: 720, lev: 181, Xdim: 97152)>
dask.array<add, shape=(720, 181, 97152), dtype=float32, chunksize=(30, 181, 1024), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 2020-01-30 ... 2020-02-28T23:00:00
    lons     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
    lats     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
  * lev      (lev) float64 1.0 2.0 3.0 4.0 5.0 ... 177.0 178.0 179.0 180.0 181.0
Dimensions without coordinates: Xdim
Attributes:
    standard_name:  air_pressure
    long_name:      pressure_of_air_at_levs
    method:         pthick cumulatively subtracted from pressure at the surface
    unit:           Pa

In [12]:
pa = xr.Dataset({"pa":pa}, attrs=pa.attrs)
pa

<xarray.Dataset>
Dimensions:  (time: 720, Xdim: 97152, lev: 181)
Coordinates:
  * time     (time) datetime64[ns] 2020-01-30 ... 2020-02-28T23:00:00
    lons     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
    lats     (Xdim) float32 dask.array<chunksize=(1024,), meta=np.ndarray>
  * lev      (lev) float64 1.0 2.0 3.0 4.0 5.0 ... 177.0 178.0 179.0 180.0 181.0
Dimensions without coordinates: Xdim
Data variables:
    pa       (time, lev, Xdim) float32 dask.array<chunksize=(30, 181, 1024), meta=np.ndarray>
Attributes:
    standard_name:  air_pressure
    long_name:      pressure_of_air_at_levs
    method:         pthick cumulatively subtracted from pressure at the surface
    unit:           Pa

In [ ]:
pa.to_netcdf("/scratch/b/b380883/TWP_3D_GEOS_pfull_20200130-20200228.nc")